name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # or main if that's your default

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Publish Blazor app
      run: dotnet publish UltimateRoster.csproj -c Release -o release

    - name: List published files
      run: |
        echo "Listing files in release/wwwroot:"
        ls -R release/wwwroot

    - name: Copy wwwroot to expected output
      run: |
        mkdir public
        cp -r release/wwwroot/* public
        touch public/.nojekyll

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
